import { SessionizeSession } from "./sessionize-sessions";

const sessions = [

      {
        questionAnswers: [],
        id: "708024",
        title: "Why your next React project needs to use Remix?",
        description:
          "Kindly receive the bellow links to our proposal and pitching video.\r\n\r\nProposal Link : https://bit.ly/4aXxkiN\r\n\r\nPitching video link :  https://bit.ly/3VvWYpc\r\n\r\n",
        startsAt: "2024-10-04T10:40:00",
        endsAt: "2024-10-04T11:25:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "413134ca-5750-4581-8e20-56ba0bc6d2cc",
            name: "Samuel Kamotho",
          },
          {
            id: "6e6e7c55-9204-4bb9-8bbf-4d8ee09fef35",
            name: "Felix Kabethi",
          },
          {
            id: "3e9d81c7-5af0-4d97-afd6-5fee078fed64",
            name: "Rodgers Wanyonyi",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "704595",
        title: "Building Native Modules With React Native",
        description:
          "My presentation will explain improving React Native apps by developing native modules. I will provide a step-by-step demonstration of integrating custom features and accessing native APIs using native code. This involves connecting JavaScript (React Native) with native languages such as Kotlin for Android and Swift for iOS.",
        startsAt: "2024-10-04T10:40:00",
        endsAt: "2024-10-04T11:25:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "c15d86ab-cddf-41e2-8006-38d8dd69482c",
            name: "Denis Kamau",
          },
        ],
        categories: [],
        roomId: 48139,
        room: "Kilifi Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "696462",
        title: "Building Tomorrow's Web with Today's Tech",
        description:
          "In this session, we will explore the advancements in the Web, delving into the origins and history of this technology.\r\n\r\nDiscover how leveraging tools such as Next.JS and Node.JS can enhance your software ideas, enabling you to deploy global solutions faster than ever before. Gain insights into real-world use cases and learn how we successfully built a scalable AI web app at Code Fundi, serving a global audience.\r\n\r\nJoin us as we explore the transformative potential of harnessing the JavaScript ecosystem to develop tomorrow's solutions, such as advancements in AI.",
        startsAt: "2024-10-04T10:40:00",
        endsAt: "2024-10-04T11:25:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "a3a8a428-45f8-450d-9ed4-450ec65bcacd",
            name: "Felix Waweru",
          },
        ],
        categories: [],
        roomId: 48140,
        room: "Diani Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "664796",
        title:
          "Beyond the Big Names: Exploring the Rich Tapestry of the React Ecosystem",
        description:
          "Sure, we've all heard of Next.js and Remix. But React's true power lies in its expansive and ever-evolving ecosystem, teeming with a diverse array of tools and libraries. This talk delves into this vibrant landscape, showcasing some of the most popular and innovative choices beyond the usual suspects.\r\n\r\nWe'll explore what makes React such a versatile library, and how these tools leverage its un opinionated nature to empower you to build exceptional user interfaces.\r\n\r\nGet ready to discover hidden gems and cutting-edge solutions that can elevate your React development experience. Whether you're a seasoned pro or just starting out, this talk will equip you with the knowledge to make informed decisions and build truly remarkable React applications.\r\n",
        startsAt: "2024-10-04T11:35:00",
        endsAt: "2024-10-04T12:20:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "ae941c1c-9902-4e57-a49e-2aa7af798132",
            name: "Dennis Waweru",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "688282",
        title:
          "Creative Thinking : How I used React state & dynamic book publisher component to write my first book",
        description:
          "The premise of this talk / premise will be to walk the Audience through how I was able to author my first book using the power of React state to enable, build a dynamic object containing all the information about my first book Creative Thinking : A journey through the 8 facets of intelligence ( dapperjd.com ), then transition the same information to a React native component built to parse the data and render it as an interactive android e-book. \r\n\r\nThe talk will walk through the following key points : \r\n\r\n1. How to build and render state dynamically in React & React Native\r\n2. The power of thinking in terms of scalability when building projects\r\n3. Understanding how to reuse components from both React and React native, maximizing on same component props & how to prepare a manuscript renderer in react.\r\n4. The Creative through process that led to challenging the traditional publishing process and how I was able to make sufficient profit margin even with traditional print approach. ",
        startsAt: "2024-10-04T11:35:00",
        endsAt: "2024-10-04T12:20:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "8dd43c8c-0135-46c5-a833-aa11313b10d2",
            name: "John Akello",
          },
        ],
        categories: [],
        roomId: 48139,
        room: "Kilifi Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "702809",
        title:
          'Empowering Diversity in Tech: Navigating Gender Equality & Team Leadership"',
        description:
          "In this dynamic and thought-provoking session, delve into the intersection of gender equality advocacy and team leadership in the tech workplace. Uncover the transformative power of diversity and inclusion as catalysts for driving innovation, collaboration, and organizational excellence.\r\n\r\n Gain invaluable insights into the tangible benefits of promoting gender equality, including enhanced decision-making, improved employee morale, and increased productivity. \r\n\r\nExplore actionable strategies and best practices for cultivating an inclusive culture that empowers individuals of all genders to thrive and excel. \r\n\r\nFrom harnessing the unique strengths of diverse teams to fostering authentic leadership and communication, this session equips attendees with the tools and knowledge to champion equality and drive positive change in their organizations.\r\n\r\n\r\n\r\n\r\n",
        startsAt: "2024-10-04T11:35:00",
        endsAt: "2024-10-04T12:20:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "8f5ac154-1193-49aa-aefb-3ace5ea8b0a7",
            name: "Lilian N. M",
          },
        ],
        categories: [],
        roomId: 48140,
        room: "Diani Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "703075",
        title:
          "Incremental Static Regeneration (ISR) with Next.js and TypeScript",
        description:
          "I will introduce the concept of Incremental Static Regeneration (ISR) in Next.js and how TypeScript can enhance the development process. Attendees will learn how to leverage ISR to build high-performance, scalable web applications that combine the best of static and dynamic rendering. Through practical examples and real-world use cases, I will demonstrate the seamless integration of ISR with TypeScript, highlighting the latest updates and features announced at React Conf.\r\n\r\nWhat Attendees Will Learn:\r\nUnderstanding ISR: A deep dive into the principles of Incremental Static Regeneration, its benefits, and its use cases.\r\nTypeScript Integration: How TypeScript can improve the development experience when working with ISR in Next.js projects.\r\nLatest Features and Updates: Insights into the newest ISR features from React Conf and how they can be applied to optimise web applications.\r\nPractical Implementation: Step-by-step examples of setting up ISR in a Next.js project with TypeScript, including best practices and common pitfalls.\r\n\r\nThis topic is highly relevant for developers looking to build modern web applications that require a balance between static and dynamic content. ISR is a powerful feature in Next.js that allows developers to update static content after the initial build without rebuilding the entire site. By integrating TypeScript, developers can enhance code quality and maintainability, making it a crucial skill set for attendees looking to stay competitive in the industry.\r\n",
        startsAt: "2024-10-04T12:30:00",
        endsAt: "2024-10-04T12:55:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "eace233d-0a55-4a1b-88f3-c5a03f503fe8",
            name: "Lorna Muchangi",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "715787",
        title: "Server Components: The Epic Tale of Rendering UX",
        description:
          "Server components, introduced in React v18 end these shortcomings, enabling rendering React components fully on the server, into an intermediate abstraction format without needing to add to the JavaScript bundle. \r\n\r\nThis talk aims to cover the following points:\r\n\r\n1. A fun story of how we needed CSR and how SSR started to take its place\r\n\r\n2. What are server components and what benefits did they bring like 0 javascript bundle size\r\n\r\n3. Demo of a simple app using client-side rendering, SSR, and server components and analyzing the performance gains and understanding when to use what\r\n\r\n4. My take on how rendering UI will change with this approach",
        startsAt: "2024-10-04T14:00:00",
        endsAt: "2024-10-04T14:25:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "0a466402-5536-4f02-9add-e681674d4e41",
            name: "Roy Wanyoike",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "694031",
        title:
          "How Effective Communication Makes Tech Magnetic: Unveiling the Hidden Language",
        description:
          "Imagine a world where technology isn't an intimidating idea, but a more vibrant conversation filled with a world of possibilities, from flying cars, Smart homes, and innovative technology. This is the power of effective communication in the realm of tech.  I want us to challenge the perception of software development as an exclusive club of nerds with their own secret language.  \r\n\r\nImagine someone passionate about solving problems, or a young member of society simply curious about technology but is hesitant to enter the tech world due to perceived complexity and scares easy-to-understand content. \r\n\r\nThis is where communication becomes an attractive force. By breaking down technical concepts into easy-to-understand language, we can begin to demystify the process and ignite a spark in those who might otherwise feel excluded.\r\n\r\n In the world of software development, communication is the lifeblood. We collaborate with designers, interact with clients, and document our work for future reference. Clear communication ensures everyone's on the same page and we can avoid costly errors, delays, or even rejection. \r\n\r\nEffective communication in tech isn't just about efficiency; it's about inclusion. We must embrace the power of clear, engaging communication to transform tech from an intimidating maze into a vibrant conversation. Let's show the world that the language of technology is not a barrier, but an invitation to participate in building a brighter, more connected future, and as the world Reacts to technology it is our duty to make it magnetic.\r\n",
        startsAt: "2024-10-04T14:00:00",
        endsAt: "2024-10-04T14:25:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "03871d0a-8e8c-4a6b-a5ba-cece505c9c23",
            name: "Keorapetse Magano",
          },
        ],
        categories: [],
        roomId: 48139,
        room: "Kilifi Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "660132",
        title: "Generative UI with Vercel v0",
        description:
          "Discover how to revolutionize user interfaces with Vercel v0's Generative UI. Learn to create dynamic, personalized experiences tailored to individual users' needs and context. Dive into the power of AI-driven React components and streamline design engineering processes. Join us to explore the future of UI design and deliver richer user experiences at scale.",
        startsAt: "2024-10-04T14:25:00",
        endsAt: "2024-10-04T15:10:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "fc2e030d-0ff8-4ba4-80bc-5ba7a2d79062",
            name: "Mark Aloo",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "692168",
        title: "Building Direct and Complete UI",
        description:
          "How to build direct and complete user experiences for your users",
        startsAt: "2024-10-04T14:25:00",
        endsAt: "2024-10-04T15:10:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "2b1d508c-03ab-47ce-b4b4-7fdd4f8e9676",
            name: "David .Amunga",
          },
        ],
        categories: [],
        roomId: 48139,
        room: "Kilifi Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "703118",
        title: "Lucia Auth on Next JS",
        description:
          "This session is designed to provide a comprehensive understanding of how to address authentication challenges using Lucia Auth within Next.js applications.\r\n\r\nWe’ll introduce Lucia Auth, a powerful and user-friendly authentication solution that offers simplicity, flexibility, and strong security features tailored for Next.js projects. Attendees will gain insights into Lucia Auth’s architecture and how it integrates seamlessly with Next.js to create a robust and reliable authentication system.\r\n\r\nIn the hands-on portion of the session, participants will be guided step-by-step through the process of setting up Lucia Auth in a Next.js project. This practical demonstration will cover everything from initial setup to advanced configurations, including best practices for managing sessions, user roles, and environment variables. We’ll also cover essential testing and debugging techniques to ensure your implementation is both secure and efficient.\r\n\r\nBy the end of this session, attendees will be equipped with the knowledge and skills needed to implement a scalable and secure authentication system in their Next.js applications using Lucia Auth. Whether you're a novice or an experienced developer, this session will elevate your understanding of modern authentication practices and provide you with practical techniques that you can apply immediately in your projects.",
        startsAt: "2024-10-04T14:25:00",
        endsAt: "2024-10-04T15:10:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "abe915e2-8ecf-4afa-8d01-94da2c24be1a",
            name: "Felix Jumason",
          },
        ],
        categories: [],
        roomId: 48140,
        room: "Diani Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "716182",
        title: "Optimizing React Native Apps",
        description:
          'In the competitive world of mobile applications, performance is paramount. Users expect seamless, fast, and responsive experiences, and any lag can result in poor reviews and lost users. This talk, "Optimizing React Native Apps: Best Practices for Peak Performance," is designed for developers who want to elevate their React Native apps to the next level.\r\n\r\nWhether you are a seasoned React Native developer or just starting, this talk will provide you with actionable insights and practical tips to make your apps perform better than ever before.',
        startsAt: "2024-10-04T15:20:00",
        endsAt: "2024-10-04T16:05:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "12f299ae-96ff-4dff-8a3d-484e68650b97",
            name: "Cliff Gor",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "714248",
        title: "Team leadership & soft skills",
        description:
          "Join me, as I explore the essential qualities of effective team leadership and the importance of soft skills in today's fast-paced business world. Drawing from my experience as an entrepreneur and digital marketing strategist, I’ll share insights on fostering a collaborative and innovative team environment, enhancing communication and emotional intelligence, and driving team performance through empathy and strategic thinking. Learn how to lead with confidence, inspire your team, and cultivate a culture of continuous growth and success.",
        startsAt: "2024-10-04T15:20:00",
        endsAt: "2024-10-04T16:05:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "b229e20c-1124-4560-b5c4-f03c5b9873c5",
            name: "Emily Maina",
          },
        ],
        categories: [],
        roomId: 48139,
        room: "Kilifi Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "697091",
        title:
          "Garra be specific bro: !important; - A guide to CSS specificity.",
        description:
          "In the ever-evolving world of web development, CSS specificity remains a crucial concept for developers aiming to create clean, and maintainable stylesheets. This is a comprehensive talk where we delve into the intricacies of CSS specificity, explore in the context of TailwindCSS, and extend our knowledge into the realm of plugin development.",
        startsAt: "2024-10-04T15:20:00",
        endsAt: "2024-10-04T16:05:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "284934dd-0986-4cfb-85da-2ea96cf2362d",
            name: "Grishon Nganga",
          },
        ],
        categories: [],
        roomId: 48140,
        room: "Diani Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "746581",
        title: "Securing Your React Native App best Practices",
        description:
          "Explore some of the most prevalent security threats facing hybrid mobile frameworks & discuss strategies for mitigating them",
        startsAt: "2024-10-05T09:40:00",
        endsAt: "2024-10-05T10:25:00",
        isServiceSession: false,
        isPlenumSession: true,
        speakers: [
          {
            id: "46dd50e7-30ce-4c11-93e4-8e12de1050d1",
            name: "Neville Oronni N/A",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "702676",
        title: "10 Lessons learnt from running server components at scale",
        description:
          "In my role as Tech lead @ Jumba (https://jum.ba), I have had the incredible opportunity to decide on what tools/technologies we use. One of these decisions included adopting Next.js app directory and RSC quite early on (from version 13.4). With this, came challenges and benefits that I have summarized into 10 lessons that we learnt from this migration in a team of ~20 devs for all our web applications",
        startsAt: "2024-10-05T10:40:00",
        endsAt: "2024-10-05T11:25:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "44725295-1920-4ace-a4aa-356cfef8947f",
            name: "Victor Ndaba",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "674965",
        title: "Sleek, Smooth, Synced: Mastering UI Animations in React Native",
        description:
          "Are you ready to elevate your mobile apps from functional to phenomenal? Whether you're working with React Native in a bare app or using Expo, join us for an advanced, hands-on session where we unlock the art of stunning animations. Perfect for developers eager to push the limits of app design, this session will teach you how to create fluid, responsive, and visually captivating animations that leave users in awe.\r\n\r\nIn this exciting session, we’ll dive deep into the world of React Native animations, exploring tools and techniques tailored for both bare apps and Expo environments. From mastering the basics of the Animated API to harnessing the full power of the Reanimated library, you’ll learn how to craft animations that not only look amazing but also enhance the overall user experience.\r\n\r\nWe’ll start with a quick overview of animation fundamentals, setting the stage for more advanced techniques that will bring your apps to life. As we delve into these powerful tools, you’ll discover how to optimize performance, ensuring that your animations are as smooth and efficient as they are stunning—whether you’re developing in a bare React Native app or within Expo.\r\n\r\nBut we won't stop at theory. Through live coding demos, you'll see these concepts in action, with practical examples that you can immediately apply to your projects—no matter your development setup.\r\n\r\nWe'll also highlight inspiring case studies from top apps that have leveraged React Native animations to captivate their audiences. Learn from their successes and discover how you can replicate their results, creating apps that stand out and engage users like never before.\r\n\r\nFinally, we’ll look ahead to the future of animations in React Native and Expo, exploring how you can stay at the cutting edge of this vibrant ecosystem. This session is designed to spark your creativity, challenge your skills, and show you just how far you can go with React Native and Expo animations.",
        startsAt: "2024-10-05T10:40:00",
        endsAt: "2024-10-05T11:25:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "32b87c69-4772-466b-96ec-efca474bb197",
            name: "Amos Nyaburi",
          },
        ],
        categories: [],
        roomId: 48139,
        room: "Kilifi Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "688026",
        title: "Exploring Prompt Engineering: Best Practices for  Developers",
        description:
          "As the field of Artificial Intelligence continues to evolve, prompt engineering emerges as a crucial skill for developers leveraging AI-powered solutions in mobile applications. This session at RenderCon Kenya 2024 delves into the art and science of prompt engineering, tailored specifically for developers. Attendees will explore the various types of prompt engineering, from basic structures to advanced techniques, and learn best practices to optimize AI interactions within mobile platforms.\r\n\r\nThe session will cover:\r\n>>An introduction to prompt engineering and its significance in AI-driven apps.\r\n>>Different types of prompts and how they influence AI responses.\r\n>>Practical guidelines for crafting effective prompts to enhance user experience and app functionality.\r\n>>Real-world examples and case studies demonstrating successful prompt engineering in mobile development.\r\nAttendees will gain valuable insights and hands-on knowledge that will empower them to integrate sophisticated AI capabilities into their applications, driving innovation and user engagement.\r\n\r\n\r\n\r\n\r\n\r\n\r\n",
        startsAt: "2024-10-05T10:40:00",
        endsAt: "2024-10-05T11:25:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "4f0f7c4d-212a-424f-b736-aef781c9a1f9",
            name: "Marjan Hussein",
          },
        ],
        categories: [],
        roomId: 48140,
        room: "Diani Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "694094",
        title: "Interview Prepping for that Big Role",
        description:
          "Engineers no longer dictate the market like in the COVID days. How do you stand out in the age of AI and a large talent pool? ",
        startsAt: "2024-10-05T11:35:00",
        endsAt: "2024-10-05T12:20:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "743f509f-4bbc-42fe-ac58-cdb56b213624",
            name: "Albina Muturi",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "715938",
        title:
          "Server Driven Development: Understanding React Server Components",
        description:
          "Learn how to move rendering to the server to improve performance, use available resources best, and ease difficult user interface problems. Use this innovative, potent technology to enhance your web and mobile applications.",
        startsAt: "2024-10-05T11:35:00",
        endsAt: "2024-10-05T12:20:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "d7fbfa55-9829-43b8-b9a2-e738d929f0fd",
            name: "Timothy Mugo",
          },
        ],
        categories: [],
        roomId: 48139,
        room: "Kilifi Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "669717",
        title: "Shipping",
        description:
          "If it's not shipped it's useless. Traditionally, or rather I would say, most developers say when it comes to shipping their react apps, they use vercel, netlify among other platforms.\r\n\r\nIf a fronted is hosted on a different platform the backend which mostly resides on cloud, one will always incur egress costs which are no joke. \r\n\r\nwhat if I told you, we can do shio these frontends on the same server, cloud, as backend and utilize internal networks and therefore not egress costs incurred.\r\n\r\n\r\nIn this session, we look how we do it, and also implement the same.\r\n\r\n#Docker\r\n#Cloud\r\n#ShipIT\r\n#React\r\n ",
        startsAt: "2024-10-05T11:35:00",
        endsAt: "2024-10-05T12:20:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "23d67e76-4586-4dfc-9f43-5b4c8ee54229",
            name: "Joseph Njogu",
          },
        ],
        categories: [],
        roomId: 48140,
        room: "Diani Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "708002",
        title: "Exploring SSR Auth with Supabase and Next.js App Router",
        description:
          "Learn about authentication with Supabase and Next.js. This talk will cover user authentication using server-side rendering (SSR) in a Next.js App Router project. It will explore auth concepts such as anonymous sign in, social login and identity linking.",
        startsAt: "2024-10-05T12:30:00",
        endsAt: "2024-10-05T12:55:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "2f1322b5-4fd8-4480-9737-1837f85f0b08",
            name: "Fatuma Abdullahi",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "707890",
        title: "Cooking up codemods to refactor legacy codebases",
        description:
          "In this session, we dive into the transformative power of codemod tools like jscodeshift to automate the tedious aspects of refactoring, easing the journey from legacy code to modern standards. We'll explore how to craft custom codemods tailored to your codebase's nuances, enabling seamless upgrades and refactoring.\r\n\r\nAttendees will learn:\r\n\r\n- The fundamentals of codemod tools in the javascript ecosystem and how they streamline refactoring and updating processes.\r\n- Case studies of using popular codemod libraries provided by frameworks like React and Next.js for version upgrades. Demonstration how we used jscodeshift to upgrade a legacy react-native v0.64 codebase\r\n- Leveraging AI to generate complex codemod transforms with tools like codemod.com\r\n\r\nDiscover how harnessing codemod tools and AI can elevate your development workflow, making complex refactoring and updates more manageable and less error-prone. Whether you're grappling with a sprawling legacy codebase or planning a strategic upgrade, this session equips you with the tools and insights to refactor faster and upgrade smarter in React and React Native projects.",
        startsAt: "2024-10-05T14:00:00",
        endsAt: "2024-10-05T14:25:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "472981dd-32bd-4ad3-8b4f-b56f09a5a6a9",
            name: "Stephen Wanyee",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "734648",
        title:
          "Taking React Server Components to Enterprise: pitfalls and learnings",
        description:
          'Description\r\n[🚧TEST SESSION 🚧 — 🚧TEST SESSION 🚧 — 🚧TEST SESSION 🚧 ]\r\nIn recent years, React Server Components have emerged as a groundbreaking paradigm shift in the world of web development. This session, titled "Taking React Server Components to Enterprise: Pitfalls and Learnings," delves into the experiences and insights gained from implementing React Server Components in large-scale enterprise projects.\r\n\r\nAs organizations increasingly adopt this cutting-edge technology, they encounter unique challenges and opportunities. In this session, we explore the common pitfalls that enterprises face when integrating React Server Components into their tech stacks. Through real-world examples and case studies, we shed light on the strategies and best practices that can help enterprises harness the full potential of this revolutionary approach to web development.\r\n\r\nFrom managing complex state and data flows to optimizing performance and ensuring seamless collaboration among development teams, this session covers a wide range of essential topics. Attendees will gain valuable insights into how to navigate the intricacies of React Server Components within an enterprise context, fostering innovation, scalability, and maintainability.\r\n\r\nJoin us for a deep dive into the enterprise adoption of React Server Components and discover the strategies that can lead to successful implementation while avoiding common stumbling blocks. Whether you are a developer, architect, or tech leader, this session promises to provide you with actionable takeaways to propel your enterprise web development projects to new heights.',
        startsAt: "2024-10-05T14:00:00",
        endsAt: "2024-10-05T14:25:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "af9d3c43-aad0-4e3e-a38f-69b4274fa891",
            name: "Rama Ochieng",
          },
        ],
        categories: [],
        roomId: 48140,
        room: "Diani Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "722676",
        title: "Advanced Vite: Tapping into the true power of vite",
        description:
          "In this talk, we'll dive deep into Vite, a lightning-fast build tool that's revolutionizing the frontend development landscape. Despite its growing popularity, many teams have yet to harness its full potential. We'll explore:\r\n\r\n1. What is Vite? An introduction to its core concepts and benefits.\r\n2. Under the Hood: How Vite achieves its remarkable speed and efficiency.\r\n3. Beyond the Basics: Extending Vite for custom workflows and advanced use cases.\r\n\r\nWhether you're a seasoned developer or just starting out, this talk will equip you with the knowledge to leverage Vite's power in your projects. Discover how this innovative toolchain can streamline your development process, boost productivity, and elevate your web applications to new heights.\r\n\r\nJoin us to uncover the untapped potential of Vite and learn why it's time to make the switch in your development stack.",
        startsAt: "2024-10-05T14:25:00",
        endsAt: "2024-10-05T15:10:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "088ade04-d28e-496a-91a9-b1e21b0e88ba",
            name: "Daniel Katungi",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "705514",
        title: "Transforming User Experience with Local-First Design",
        description:
          "In today's digital age, consistent internet connectivity cannot always be guaranteed, especially in remote or underserved areas. To address this challenge, the offline-first design paradigm has emerged as a vital approach in software development. This method enables applications to function seamlessly without relying on constant internet access, ensuring a robust and uninterrupted user experience.\r\nLocal-First applications store data locally on the user's device, allowing core features to remain accessible even when the internet is unavailable. Once connectivity is restored, the app synchronizes offline changes with a remote server, maintaining data consistency and integrity. This approach contrasts sharply with the traditional model, which often restricts or disables functionalities in the absence of an internet connection, leading to a compromised user experience.\r\n\r\nThis talk will delve into the principles and advantages of Local-first design, illustrating how it can be implemented effectively in various applications. By adopting this strategy, developers can create resilient, user-friendly applications that enhance accessibility and reliability, regardless of internet connectivity. Join us to explore how Local-first design is transforming the way we build and use software in our increasingly mobile and interconnected world.",
        startsAt: "2024-10-05T14:25:00",
        endsAt: "2024-10-05T15:10:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "0e54a051-a364-4004-b4f4-15e12ec339be",
            name: "Moracha Jacob",
          },
        ],
        categories: [],
        roomId: 48139,
        room: "Kilifi Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "659329",
        title: "Next.js in Azure + CosmosDB for CRUD",
        description:
          "In this session, we’ll explore building a robust web application using Next.js, and hosting it on Microsoft Azure, while integrating essential CRUD functionality. \r\n\r\nWe’ll dive into Next.js, discuss concepts like server-side rendering (SSR) and server actions, and explore Azure deployment options. Additionally, we’ll seamlessly integrate CosmosDB, Microsoft’s globally distributed database service, for data persistence. \r\n\r\nThroughout the session, we’ll emphasize security, authentication, and real-world use cases, bridging frontend magic with backend scalability.",
        startsAt: "2024-10-05T15:20:00",
        endsAt: "2024-10-05T16:05:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "3ccb3d01-eaff-4aa8-9972-30118da3d1f4",
            name: "Mark Gatere",
          },
        ],
        categories: [],
        roomId: 48138,
        room: "Main Auditorium",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
      {
        questionAnswers: [],
        id: "701608",
        title: "Web3 Authentication",
        description: "Web3 authentication using internet identity in React",
        startsAt: "2024-10-05T15:20:00",
        endsAt: "2024-10-05T16:05:00",
        isServiceSession: false,
        isPlenumSession: false,
        speakers: [
          {
            id: "4bf01bdb-86f0-41aa-8578-c7a2d0422e89",
            name: "Cosmas💙 Ken",
          },
        ],
        categories: [],
        roomId: 48139,
        room: "Kilifi Breakout",
        liveUrl: null,
        recordingUrl: null,
        status: "Accepted",
        isInformed: true,
        isConfirmed: true,
      },
    ] 

    const sessionsGroupedByStartingTime: Record<string, SessionizeSession[]> = sessions.reduce((acc, session) => {
      const key = session.startsAt
      acc[key] = [...(acc[key as string] || []), session as any as SessionizeSession]
      return acc
    }, {} as Record<string, SessionizeSession[]>);



